// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package goalsdb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateGoal(ctx context.Context, arg CreateGoalParams) (CreateGoalRow, error)
	DeleteGoal(ctx context.Context, arg DeleteGoalParams) (int64, error)
	ListGoals(ctx context.Context, accountID uuid.UUID) ([]ListGoalsRow, error)
	UpdateGoalFields(ctx context.Context, arg UpdateGoalFieldsParams) (int64, error)
	UpdateGoalProgress(ctx context.Context, arg UpdateGoalProgressParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
