// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package goalsdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAssignableGoal = `-- name: CountAssignableGoal :one
SELECT count(*)
FROM goals
WHERE account_id = $1 AND id = $2
`

type CountAssignableGoalParams struct {
	AccountID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) CountAssignableGoal(ctx context.Context, arg CountAssignableGoalParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAssignableGoal, arg.AccountID, arg.ID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGoalsByCategory = `-- name: CountGoalsByCategory :many
SELECT category_id, count(*) AS total
FROM goals
WHERE account_id = $1 AND category_id IS NOT NULL
GROUP BY category_id
`

type CountGoalsByCategoryRow struct {
	CategoryID pgtype.UUID
	Total      int64
}

func (q *Queries) CountGoalsByCategory(ctx context.Context, accountID uuid.UUID) ([]CountGoalsByCategoryRow, error) {
	rows, err := q.db.Query(ctx, countGoalsByCategory, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountGoalsByCategoryRow{}
	for rows.Next() {
		var i CountGoalsByCategoryRow
		if err := rows.Scan(&i.CategoryID, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createGoal = `-- name: CreateGoal :one
INSERT INTO goals (account_id, title, description, target_date, category_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, title, description, target_date, progress, category_id, created_at, updated_at
`

type CreateGoalParams struct {
	AccountID   uuid.UUID
	Title       string
	Description pgtype.Text
	TargetDate  pgtype.Date
	CategoryID  pgtype.UUID
}

type CreateGoalRow struct {
	ID          uuid.UUID
	Title       string
	Description pgtype.Text
	TargetDate  pgtype.Date
	Progress    string
	CategoryID  pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateGoal(ctx context.Context, arg CreateGoalParams) (CreateGoalRow, error) {
	row := q.db.QueryRow(ctx, createGoal,
		arg.AccountID,
		arg.Title,
		arg.Description,
		arg.TargetDate,
		arg.CategoryID,
	)
	var i CreateGoalRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.TargetDate,
		&i.Progress,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGoal = `-- name: DeleteGoal :execrows
DELETE FROM goals WHERE account_id = $1 AND id = $2
`

type DeleteGoalParams struct {
	AccountID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) DeleteGoal(ctx context.Context, arg DeleteGoalParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGoal, arg.AccountID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listGoals = `-- name: ListGoals :many
SELECT id, title, description, target_date, progress, category_id, created_at, updated_at
FROM goals
WHERE account_id = $1
ORDER BY created_at DESC, id
`

type ListGoalsRow struct {
	ID          uuid.UUID
	Title       string
	Description pgtype.Text
	TargetDate  pgtype.Date
	Progress    string
	CategoryID  pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) ListGoals(ctx context.Context, accountID uuid.UUID) ([]ListGoalsRow, error) {
	rows, err := q.db.Query(ctx, listGoals, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGoalsRow{}
	for rows.Next() {
		var i ListGoalsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.TargetDate,
			&i.Progress,
			&i.CategoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGoalFields = `-- name: UpdateGoalFields :execrows
UPDATE goals
SET title = $3, description = $4, target_date = $5, category_id = $6, updated_at = now()
WHERE account_id = $1 AND id = $2
`

type UpdateGoalFieldsParams struct {
	AccountID   uuid.UUID
	ID          uuid.UUID
	Title       string
	Description pgtype.Text
	TargetDate  pgtype.Date
	CategoryID  pgtype.UUID
}

func (q *Queries) UpdateGoalFields(ctx context.Context, arg UpdateGoalFieldsParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateGoalFields,
		arg.AccountID,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.TargetDate,
		arg.CategoryID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateGoalProgress = `-- name: UpdateGoalProgress :execrows
UPDATE goals
SET progress = $3, updated_at = now()
WHERE account_id = $1 AND id = $2
`

type UpdateGoalProgressParams struct {
	AccountID uuid.UUID
	ID        uuid.UUID
	Progress  string
}

func (q *Queries) UpdateGoalProgress(ctx context.Context, arg UpdateGoalProgressParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateGoalProgress, arg.AccountID, arg.ID, arg.Progress)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
