version: "2"

linters:
  default: standard
  enable:
    - bodyclose
    - errorlint
    - gosec
    - misspell
    - revive
    - unconvert
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gosec
          - errcheck
          - bodyclose

formatters:
  enable:
    - gofmt
