// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package categoriesdb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ArchiveCategory(ctx context.Context, arg ArchiveCategoryParams) (int64, error)
	CountAssignableCategory(ctx context.Context, arg CountAssignableCategoryParams) (int64, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (CreateCategoryRow, error)
	// Read-before-write for the partial Update (R3) — merges a caller's provided
	// fields onto the current row before the full-replace UpdateCategory write below.
	GetActiveCategory(ctx context.Context, arg GetActiveCategoryParams) (GetActiveCategoryRow, error)
	ListActiveCategories(ctx context.Context, accountID uuid.UUID) ([]ListActiveCategoriesRow, error)
	// Active and archived, for M8 export completeness.
	ListAllCategories(ctx context.Context, accountID uuid.UUID) ([]ListAllCategoriesRow, error)
	ListCategoryNames(ctx context.Context, accountID uuid.UUID) ([]ListCategoryNamesRow, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
