// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package categoriesdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archiveCategory = `-- name: ArchiveCategory :execrows
UPDATE categories
SET archived_at = now()
WHERE account_id = $1 AND id = $2 AND archived_at IS NULL
`

type ArchiveCategoryParams struct {
	AccountID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) ArchiveCategory(ctx context.Context, arg ArchiveCategoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, archiveCategory, arg.AccountID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countAssignableCategory = `-- name: CountAssignableCategory :one
SELECT count(*)
FROM categories
WHERE account_id = $1 AND id = $2 AND archived_at IS NULL
`

type CountAssignableCategoryParams struct {
	AccountID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) CountAssignableCategory(ctx context.Context, arg CountAssignableCategoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAssignableCategory, arg.AccountID, arg.ID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (account_id, name, colour, icon)
VALUES ($1, $2, $3, $4)
RETURNING id, name, COALESCE(colour, '')::text AS colour, COALESCE(icon, '')::text AS icon, archived_at, created_at
`

type CreateCategoryParams struct {
	AccountID uuid.UUID
	Name      string
	Colour    pgtype.Text
	Icon      pgtype.Text
}

type CreateCategoryRow struct {
	ID         uuid.UUID
	Name       string
	Colour     string
	Icon       string
	ArchivedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (CreateCategoryRow, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.AccountID,
		arg.Name,
		arg.Colour,
		arg.Icon,
	)
	var i CreateCategoryRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Colour,
		&i.Icon,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveCategory = `-- name: GetActiveCategory :one
SELECT id, name, COALESCE(colour, '')::text AS colour, COALESCE(icon, '')::text AS icon, archived_at, created_at
FROM categories
WHERE account_id = $1 AND id = $2 AND archived_at IS NULL
`

type GetActiveCategoryParams struct {
	AccountID uuid.UUID
	ID        uuid.UUID
}

type GetActiveCategoryRow struct {
	ID         uuid.UUID
	Name       string
	Colour     string
	Icon       string
	ArchivedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

// Read-before-write for the partial Update (R3) — merges a caller's provided
// fields onto the current row before the full-replace UpdateCategory write below.
func (q *Queries) GetActiveCategory(ctx context.Context, arg GetActiveCategoryParams) (GetActiveCategoryRow, error) {
	row := q.db.QueryRow(ctx, getActiveCategory, arg.AccountID, arg.ID)
	var i GetActiveCategoryRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Colour,
		&i.Icon,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveCategories = `-- name: ListActiveCategories :many
SELECT id, name, COALESCE(colour, '')::text AS colour, COALESCE(icon, '')::text AS icon, archived_at, created_at
FROM categories
WHERE account_id = $1 AND archived_at IS NULL
ORDER BY lower(name)
`

type ListActiveCategoriesRow struct {
	ID         uuid.UUID
	Name       string
	Colour     string
	Icon       string
	ArchivedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) ListActiveCategories(ctx context.Context, accountID uuid.UUID) ([]ListActiveCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listActiveCategories, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveCategoriesRow{}
	for rows.Next() {
		var i ListActiveCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Colour,
			&i.Icon,
			&i.ArchivedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllCategories = `-- name: ListAllCategories :many
SELECT id, name, COALESCE(colour, '')::text AS colour, COALESCE(icon, '')::text AS icon, archived_at, created_at
FROM categories
WHERE account_id = $1
ORDER BY lower(name)
`

type ListAllCategoriesRow struct {
	ID         uuid.UUID
	Name       string
	Colour     string
	Icon       string
	ArchivedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

// Active and archived, for M8 export completeness.
func (q *Queries) ListAllCategories(ctx context.Context, accountID uuid.UUID) ([]ListAllCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listAllCategories, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllCategoriesRow{}
	for rows.Next() {
		var i ListAllCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Colour,
			&i.Icon,
			&i.ArchivedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoryNames = `-- name: ListCategoryNames :many
SELECT id, name
FROM categories
WHERE account_id = $1
`

type ListCategoryNamesRow struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) ListCategoryNames(ctx context.Context, accountID uuid.UUID) ([]ListCategoryNamesRow, error) {
	rows, err := q.db.Query(ctx, listCategoryNames, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCategoryNamesRow{}
	for rows.Next() {
		var i ListCategoryNamesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :execrows
UPDATE categories
SET name = $3, colour = $4, icon = $5
WHERE account_id = $1 AND id = $2 AND archived_at IS NULL
`

type UpdateCategoryParams struct {
	AccountID uuid.UUID
	ID        uuid.UUID
	Name      string
	Colour    pgtype.Text
	Icon      pgtype.Text
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCategory,
		arg.AccountID,
		arg.ID,
		arg.Name,
		arg.Colour,
		arg.Icon,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
