// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package accountdb

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	Timezone     string
	CreatedAt    pgtype.Timestamptz
}

type Session struct {
	Token      string
	AccountID  uuid.UUID
	CreatedAt  pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
}
