// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package accountdb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (CreateAccountRow, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	DeleteAccountSessions(ctx context.Context, accountID uuid.UUID) error
	DeleteSession(ctx context.Context, token string) error
	GetAccountByEmail(ctx context.Context, email string) (Account, error)
	GetAccountByID(ctx context.Context, id uuid.UUID) (GetAccountByIDRow, error)
	GetAccountPasswordHash(ctx context.Context, id uuid.UUID) (string, error)
	GetSession(ctx context.Context, token string) (Session, error)
	TouchSession(ctx context.Context, token string) error
	UpdateAccountPassword(ctx context.Context, arg UpdateAccountPasswordParams) error
	UpdateAccountTimezone(ctx context.Context, arg UpdateAccountTimezoneParams) error
}

var _ Querier = (*Queries)(nil)
