// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package accountdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (email, password_hash, timezone)
VALUES ($1, $2, $3)
RETURNING id, email, timezone, created_at
`

type CreateAccountParams struct {
	Email        string
	PasswordHash string
	Timezone     string
}

type CreateAccountRow struct {
	ID        uuid.UUID
	Email     string
	Timezone  string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (CreateAccountRow, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.Email, arg.PasswordHash, arg.Timezone)
	var i CreateAccountRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Timezone,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (token, account_id, expires_at)
VALUES ($1, $2, $3)
RETURNING token, account_id, created_at, expires_at, last_seen_at
`

type CreateSessionParams struct {
	Token     string
	AccountID uuid.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.Token, arg.AccountID, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.Token,
		&i.AccountID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
	)
	return i, err
}

const deleteAccountSessions = `-- name: DeleteAccountSessions :exec
DELETE FROM sessions WHERE account_id = $1
`

func (q *Queries) DeleteAccountSessions(ctx context.Context, accountID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAccountSessions, accountID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token = $1
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteSession, token)
	return err
}

const getAccountByEmail = `-- name: GetAccountByEmail :one
SELECT id, email, password_hash, timezone, created_at
FROM accounts
WHERE email = $1
`

func (q *Queries) GetAccountByEmail(ctx context.Context, email string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByEmail, email)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Timezone,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, email, timezone, created_at
FROM accounts
WHERE id = $1
`

type GetAccountByIDRow struct {
	ID        uuid.UUID
	Email     string
	Timezone  string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) GetAccountByID(ctx context.Context, id uuid.UUID) (GetAccountByIDRow, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i GetAccountByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Timezone,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountPasswordHash = `-- name: GetAccountPasswordHash :one
SELECT password_hash
FROM accounts
WHERE id = $1
`

func (q *Queries) GetAccountPasswordHash(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getAccountPasswordHash, id)
	var password_hash string
	err := row.Scan(&password_hash)
	return password_hash, err
}

const getSession = `-- name: GetSession :one
SELECT token, account_id, created_at, expires_at, last_seen_at
FROM sessions
WHERE token = $1
`

func (q *Queries) GetSession(ctx context.Context, token string) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, token)
	var i Session
	err := row.Scan(
		&i.Token,
		&i.AccountID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = now() WHERE token = $1
`

func (q *Queries) TouchSession(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, touchSession, token)
	return err
}

const updateAccountPassword = `-- name: UpdateAccountPassword :exec
UPDATE accounts SET password_hash = $2 WHERE id = $1
`

type UpdateAccountPasswordParams struct {
	ID           uuid.UUID
	PasswordHash string
}

func (q *Queries) UpdateAccountPassword(ctx context.Context, arg UpdateAccountPasswordParams) error {
	_, err := q.db.Exec(ctx, updateAccountPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateAccountTimezone = `-- name: UpdateAccountTimezone :exec
UPDATE accounts SET timezone = $2 WHERE id = $1
`

type UpdateAccountTimezoneParams struct {
	ID       uuid.UUID
	Timezone string
}

func (q *Queries) UpdateAccountTimezone(ctx context.Context, arg UpdateAccountTimezoneParams) error {
	_, err := q.db.Exec(ctx, updateAccountTimezone, arg.ID, arg.Timezone)
	return err
}
