// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package notesdb

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	Timezone     string
	CreatedAt    pgtype.Timestamptz
}

type Category struct {
	ID         uuid.UUID
	AccountID  uuid.UUID
	Name       string
	ArchivedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	Colour     pgtype.Text
	Icon       pgtype.Text
}

type DailyReview struct {
	ID        uuid.UUID
	AccountID uuid.UUID
	OnDate    pgtype.Date
	Answers   []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Goal struct {
	ID          uuid.UUID
	AccountID   uuid.UUID
	Title       string
	Description pgtype.Text
	TargetDate  pgtype.Date
	Progress    string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	CategoryID  pgtype.UUID
}

type Habit struct {
	ID         uuid.UUID
	AccountID  uuid.UUID
	Name       string
	ArchivedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	CategoryID pgtype.UUID
	Target     pgtype.Text
}

type HabitCompletion struct {
	ID        uuid.UUID
	HabitID   uuid.UUID
	AccountID uuid.UUID
	OnDate    pgtype.Date
	CreatedAt pgtype.Timestamptz
}

type Note struct {
	ID        uuid.UUID
	AccountID uuid.UUID
	Title     string
	Body      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Session struct {
	Token      string
	AccountID  uuid.UUID
	CreatedAt  pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
}

type Task struct {
	ID          uuid.UUID
	AccountID   uuid.UUID
	Title       string
	Description pgtype.Text
	DueDate     pgtype.Date
	State       string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	CategoryID  pgtype.UUID
	GoalID      pgtype.UUID
	Priority    pgtype.Text
}

type TaskTransition struct {
	ID        uuid.UUID
	TaskID    uuid.UUID
	AccountID uuid.UUID
	FromState pgtype.Text
	ToState   string
	At        pgtype.Timestamptz
}

type TimeBlock struct {
	ID         uuid.UUID
	AccountID  uuid.UUID
	Kind       string
	StartsAt   pgtype.Timestamptz
	EndsAt     pgtype.Timestamptz
	CategoryID pgtype.UUID
	CreatedAt  pgtype.Timestamptz
	TaskID     pgtype.UUID
}

type WeeklyReview struct {
	ID        uuid.UUID
	AccountID uuid.UUID
	IsoYear   int32
	IsoWeek   int32
	Answers   []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
