// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package notesdb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateNote(ctx context.Context, arg CreateNoteParams) (CreateNoteRow, error)
	DeleteNote(ctx context.Context, arg DeleteNoteParams) (int64, error)
	ListNotes(ctx context.Context, accountID uuid.UUID) ([]ListNotesRow, error)
	UpdateNoteFields(ctx context.Context, arg UpdateNoteFieldsParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
