// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package notesdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createNote = `-- name: CreateNote :one
INSERT INTO notes (account_id, title, body)
VALUES ($1, $2, $3)
RETURNING id, title, body, created_at, updated_at
`

type CreateNoteParams struct {
	AccountID uuid.UUID
	Title     string
	Body      string
}

type CreateNoteRow struct {
	ID        uuid.UUID
	Title     string
	Body      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (CreateNoteRow, error) {
	row := q.db.QueryRow(ctx, createNote, arg.AccountID, arg.Title, arg.Body)
	var i CreateNoteRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNote = `-- name: DeleteNote :execrows
DELETE FROM notes WHERE account_id = $1 AND id = $2
`

type DeleteNoteParams struct {
	AccountID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) DeleteNote(ctx context.Context, arg DeleteNoteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNote, arg.AccountID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listNotes = `-- name: ListNotes :many
SELECT id, title, body, created_at, updated_at
FROM notes
WHERE account_id = $1
ORDER BY created_at DESC, id
`

type ListNotesRow struct {
	ID        uuid.UUID
	Title     string
	Body      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ListNotes(ctx context.Context, accountID uuid.UUID) ([]ListNotesRow, error) {
	rows, err := q.db.Query(ctx, listNotes, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotesRow{}
	for rows.Next() {
		var i ListNotesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNoteFields = `-- name: UpdateNoteFields :execrows
UPDATE notes
SET title = $3, body = $4, updated_at = now()
WHERE account_id = $1 AND id = $2
`

type UpdateNoteFieldsParams struct {
	AccountID uuid.UUID
	ID        uuid.UUID
	Title     string
	Body      string
}

func (q *Queries) UpdateNoteFields(ctx context.Context, arg UpdateNoteFieldsParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateNoteFields,
		arg.AccountID,
		arg.ID,
		arg.Title,
		arg.Body,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
