// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package reviewsdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getDailyReview = `-- name: GetDailyReview :one
SELECT answers, updated_at
FROM daily_reviews
WHERE account_id = $1 AND on_date = $2
`

type GetDailyReviewParams struct {
	AccountID uuid.UUID
	OnDate    pgtype.Date
}

type GetDailyReviewRow struct {
	Answers   []byte
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetDailyReview(ctx context.Context, arg GetDailyReviewParams) (GetDailyReviewRow, error) {
	row := q.db.QueryRow(ctx, getDailyReview, arg.AccountID, arg.OnDate)
	var i GetDailyReviewRow
	err := row.Scan(&i.Answers, &i.UpdatedAt)
	return i, err
}

const getWeeklyReview = `-- name: GetWeeklyReview :one
SELECT answers, updated_at
FROM weekly_reviews
WHERE account_id = $1 AND iso_year = $2 AND iso_week = $3
`

type GetWeeklyReviewParams struct {
	AccountID uuid.UUID
	IsoYear   int32
	IsoWeek   int32
}

type GetWeeklyReviewRow struct {
	Answers   []byte
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetWeeklyReview(ctx context.Context, arg GetWeeklyReviewParams) (GetWeeklyReviewRow, error) {
	row := q.db.QueryRow(ctx, getWeeklyReview, arg.AccountID, arg.IsoYear, arg.IsoWeek)
	var i GetWeeklyReviewRow
	err := row.Scan(&i.Answers, &i.UpdatedAt)
	return i, err
}

const listAllDailyReviews = `-- name: ListAllDailyReviews :many
SELECT on_date, answers, updated_at
FROM daily_reviews
WHERE account_id = $1
ORDER BY on_date
`

type ListAllDailyReviewsRow struct {
	OnDate    pgtype.Date
	Answers   []byte
	UpdatedAt pgtype.Timestamptz
}

// Every saved daily review, for M8 export completeness.
func (q *Queries) ListAllDailyReviews(ctx context.Context, accountID uuid.UUID) ([]ListAllDailyReviewsRow, error) {
	rows, err := q.db.Query(ctx, listAllDailyReviews, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllDailyReviewsRow{}
	for rows.Next() {
		var i ListAllDailyReviewsRow
		if err := rows.Scan(&i.OnDate, &i.Answers, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllWeeklyReviews = `-- name: ListAllWeeklyReviews :many
SELECT iso_year, iso_week, answers, updated_at
FROM weekly_reviews
WHERE account_id = $1
ORDER BY iso_year, iso_week
`

type ListAllWeeklyReviewsRow struct {
	IsoYear   int32
	IsoWeek   int32
	Answers   []byte
	UpdatedAt pgtype.Timestamptz
}

// Every saved weekly review, for M8 export completeness.
func (q *Queries) ListAllWeeklyReviews(ctx context.Context, accountID uuid.UUID) ([]ListAllWeeklyReviewsRow, error) {
	rows, err := q.db.Query(ctx, listAllWeeklyReviews, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllWeeklyReviewsRow{}
	for rows.Next() {
		var i ListAllWeeklyReviewsRow
		if err := rows.Scan(
			&i.IsoYear,
			&i.IsoWeek,
			&i.Answers,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDailyReview = `-- name: UpsertDailyReview :one
INSERT INTO daily_reviews (account_id, on_date, answers)
VALUES ($1, $2, $3)
ON CONFLICT (account_id, on_date) DO UPDATE
SET answers = EXCLUDED.answers, updated_at = now()
RETURNING updated_at
`

type UpsertDailyReviewParams struct {
	AccountID uuid.UUID
	OnDate    pgtype.Date
	Answers   []byte
}

func (q *Queries) UpsertDailyReview(ctx context.Context, arg UpsertDailyReviewParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, upsertDailyReview, arg.AccountID, arg.OnDate, arg.Answers)
	var updated_at pgtype.Timestamptz
	err := row.Scan(&updated_at)
	return updated_at, err
}

const upsertWeeklyReview = `-- name: UpsertWeeklyReview :one
INSERT INTO weekly_reviews (account_id, iso_year, iso_week, answers)
VALUES ($1, $2, $3, $4)
ON CONFLICT (account_id, iso_year, iso_week) DO UPDATE
SET answers = EXCLUDED.answers, updated_at = now()
RETURNING updated_at
`

type UpsertWeeklyReviewParams struct {
	AccountID uuid.UUID
	IsoYear   int32
	IsoWeek   int32
	Answers   []byte
}

func (q *Queries) UpsertWeeklyReview(ctx context.Context, arg UpsertWeeklyReviewParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, upsertWeeklyReview,
		arg.AccountID,
		arg.IsoYear,
		arg.IsoWeek,
		arg.Answers,
	)
	var updated_at pgtype.Timestamptz
	err := row.Scan(&updated_at)
	return updated_at, err
}
