// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package reviewsdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetDailyReview(ctx context.Context, arg GetDailyReviewParams) (GetDailyReviewRow, error)
	GetWeeklyReview(ctx context.Context, arg GetWeeklyReviewParams) (GetWeeklyReviewRow, error)
	// Every saved daily review, for M8 export completeness.
	ListAllDailyReviews(ctx context.Context, accountID uuid.UUID) ([]ListAllDailyReviewsRow, error)
	// Every saved weekly review, for M8 export completeness.
	ListAllWeeklyReviews(ctx context.Context, accountID uuid.UUID) ([]ListAllWeeklyReviewsRow, error)
	UpsertDailyReview(ctx context.Context, arg UpsertDailyReviewParams) (pgtype.Timestamptz, error)
	UpsertWeeklyReview(ctx context.Context, arg UpsertWeeklyReviewParams) (pgtype.Timestamptz, error)
}

var _ Querier = (*Queries)(nil)
