// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package tasksdb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateTask(ctx context.Context, arg CreateTaskParams) (CreateTaskRow, error)
	DeleteTask(ctx context.Context, arg DeleteTaskParams) (int64, error)
	GetTaskState(ctx context.Context, arg GetTaskStateParams) (string, error)
	ListTasks(ctx context.Context, accountID uuid.UUID) ([]ListTasksRow, error)
	RecordTransition(ctx context.Context, arg RecordTransitionParams) error
	UpdateTaskFields(ctx context.Context, arg UpdateTaskFieldsParams) (int64, error)
	UpdateTaskState(ctx context.Context, arg UpdateTaskStateParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
