// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package tasksdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (account_id, title, description, due_date, state)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, title, description, due_date, state, created_at, updated_at
`

type CreateTaskParams struct {
	AccountID   uuid.UUID
	Title       string
	Description pgtype.Text
	DueDate     pgtype.Date
	State       string
}

type CreateTaskRow struct {
	ID          uuid.UUID
	Title       string
	Description pgtype.Text
	DueDate     pgtype.Date
	State       string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (CreateTaskRow, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.AccountID,
		arg.Title,
		arg.Description,
		arg.DueDate,
		arg.State,
	)
	var i CreateTaskRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.DueDate,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :execrows
DELETE FROM tasks
WHERE account_id = $1 AND id = $2
`

type DeleteTaskParams struct {
	AccountID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) DeleteTask(ctx context.Context, arg DeleteTaskParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTask, arg.AccountID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTaskState = `-- name: GetTaskState :one
SELECT state
FROM tasks
WHERE account_id = $1 AND id = $2
`

type GetTaskStateParams struct {
	AccountID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetTaskState(ctx context.Context, arg GetTaskStateParams) (string, error) {
	row := q.db.QueryRow(ctx, getTaskState, arg.AccountID, arg.ID)
	var state string
	err := row.Scan(&state)
	return state, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, title, description, due_date, state, created_at, updated_at
FROM tasks
WHERE account_id = $1
ORDER BY created_at DESC, id
`

type ListTasksRow struct {
	ID          uuid.UUID
	Title       string
	Description pgtype.Text
	DueDate     pgtype.Date
	State       string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) ListTasks(ctx context.Context, accountID uuid.UUID) ([]ListTasksRow, error) {
	rows, err := q.db.Query(ctx, listTasks, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTasksRow{}
	for rows.Next() {
		var i ListTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.DueDate,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordTransition = `-- name: RecordTransition :exec
INSERT INTO task_transitions (task_id, account_id, from_state, to_state)
VALUES ($1, $2, $3, $4)
`

type RecordTransitionParams struct {
	TaskID    uuid.UUID
	AccountID uuid.UUID
	FromState pgtype.Text
	ToState   string
}

func (q *Queries) RecordTransition(ctx context.Context, arg RecordTransitionParams) error {
	_, err := q.db.Exec(ctx, recordTransition,
		arg.TaskID,
		arg.AccountID,
		arg.FromState,
		arg.ToState,
	)
	return err
}

const updateTaskFields = `-- name: UpdateTaskFields :execrows
UPDATE tasks
SET title = $3, description = $4, due_date = $5, updated_at = now()
WHERE account_id = $1 AND id = $2
`

type UpdateTaskFieldsParams struct {
	AccountID   uuid.UUID
	ID          uuid.UUID
	Title       string
	Description pgtype.Text
	DueDate     pgtype.Date
}

func (q *Queries) UpdateTaskFields(ctx context.Context, arg UpdateTaskFieldsParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTaskFields,
		arg.AccountID,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.DueDate,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTaskState = `-- name: UpdateTaskState :execrows
UPDATE tasks
SET state = $3, updated_at = now()
WHERE account_id = $1 AND id = $2
`

type UpdateTaskStateParams struct {
	AccountID uuid.UUID
	ID        uuid.UUID
	State     string
}

func (q *Queries) UpdateTaskState(ctx context.Context, arg UpdateTaskStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTaskState, arg.AccountID, arg.ID, arg.State)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
