// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package habitsdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createHabit = `-- name: CreateHabit :one
INSERT INTO habits (account_id, name)
VALUES ($1, $2)
RETURNING id, name, archived_at, created_at
`

type CreateHabitParams struct {
	AccountID uuid.UUID
	Name      string
}

type CreateHabitRow struct {
	ID         uuid.UUID
	Name       string
	ArchivedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) CreateHabit(ctx context.Context, arg CreateHabitParams) (CreateHabitRow, error) {
	row := q.db.QueryRow(ctx, createHabit, arg.AccountID, arg.Name)
	var i CreateHabitRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const habitBelongsToAccount = `-- name: HabitBelongsToAccount :one
SELECT count(*)
FROM habits
WHERE account_id = $1 AND id = $2
`

type HabitBelongsToAccountParams struct {
	AccountID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) HabitBelongsToAccount(ctx context.Context, arg HabitBelongsToAccountParams) (int64, error) {
	row := q.db.QueryRow(ctx, habitBelongsToAccount, arg.AccountID, arg.ID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listActiveHabits = `-- name: ListActiveHabits :many
SELECT id, name, archived_at, created_at
FROM habits
WHERE account_id = $1 AND archived_at IS NULL
ORDER BY lower(name), created_at
`

type ListActiveHabitsRow struct {
	ID         uuid.UUID
	Name       string
	ArchivedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) ListActiveHabits(ctx context.Context, accountID uuid.UUID) ([]ListActiveHabitsRow, error) {
	rows, err := q.db.Query(ctx, listActiveHabits, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveHabitsRow{}
	for rows.Next() {
		var i ListActiveHabitsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ArchivedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArchivedHabits = `-- name: ListArchivedHabits :many
SELECT id, name, archived_at, created_at
FROM habits
WHERE account_id = $1 AND archived_at IS NOT NULL
ORDER BY lower(name), created_at
`

type ListArchivedHabitsRow struct {
	ID         uuid.UUID
	Name       string
	ArchivedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) ListArchivedHabits(ctx context.Context, accountID uuid.UUID) ([]ListArchivedHabitsRow, error) {
	rows, err := q.db.Query(ctx, listArchivedHabits, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArchivedHabitsRow{}
	for rows.Next() {
		var i ListArchivedHabitsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ArchivedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompletionDatesSince = `-- name: ListCompletionDatesSince :many
SELECT on_date
FROM habit_completions
WHERE habit_id = $1 AND on_date >= $2
ORDER BY on_date
`

type ListCompletionDatesSinceParams struct {
	HabitID uuid.UUID
	Since   pgtype.Date
}

func (q *Queries) ListCompletionDatesSince(ctx context.Context, arg ListCompletionDatesSinceParams) ([]pgtype.Date, error) {
	rows, err := q.db.Query(ctx, listCompletionDatesSince, arg.HabitID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Date{}
	for rows.Next() {
		var on_date pgtype.Date
		if err := rows.Scan(&on_date); err != nil {
			return nil, err
		}
		items = append(items, on_date)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCompletion = `-- name: MarkCompletion :exec
INSERT INTO habit_completions (habit_id, account_id, on_date)
VALUES ($1, $2, $3)
ON CONFLICT (habit_id, on_date) DO NOTHING
`

type MarkCompletionParams struct {
	HabitID   uuid.UUID
	AccountID uuid.UUID
	OnDate    pgtype.Date
}

func (q *Queries) MarkCompletion(ctx context.Context, arg MarkCompletionParams) error {
	_, err := q.db.Exec(ctx, markCompletion, arg.HabitID, arg.AccountID, arg.OnDate)
	return err
}

const setHabitArchived = `-- name: SetHabitArchived :execrows
UPDATE habits
SET archived_at = $3
WHERE account_id = $1 AND id = $2
`

type SetHabitArchivedParams struct {
	AccountID  uuid.UUID
	ID         uuid.UUID
	ArchivedAt pgtype.Timestamptz
}

func (q *Queries) SetHabitArchived(ctx context.Context, arg SetHabitArchivedParams) (int64, error) {
	result, err := q.db.Exec(ctx, setHabitArchived, arg.AccountID, arg.ID, arg.ArchivedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unmarkCompletion = `-- name: UnmarkCompletion :exec
DELETE FROM habit_completions
WHERE habit_id = $1 AND on_date = $2
`

type UnmarkCompletionParams struct {
	HabitID uuid.UUID
	OnDate  pgtype.Date
}

func (q *Queries) UnmarkCompletion(ctx context.Context, arg UnmarkCompletionParams) error {
	_, err := q.db.Exec(ctx, unmarkCompletion, arg.HabitID, arg.OnDate)
	return err
}
