// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package habitsdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateHabit(ctx context.Context, arg CreateHabitParams) (CreateHabitRow, error)
	HabitBelongsToAccount(ctx context.Context, arg HabitBelongsToAccountParams) (int64, error)
	ListActiveHabits(ctx context.Context, accountID uuid.UUID) ([]ListActiveHabitsRow, error)
	ListArchivedHabits(ctx context.Context, accountID uuid.UUID) ([]ListArchivedHabitsRow, error)
	ListCompletionDatesSince(ctx context.Context, arg ListCompletionDatesSinceParams) ([]pgtype.Date, error)
	MarkCompletion(ctx context.Context, arg MarkCompletionParams) error
	SetHabitArchived(ctx context.Context, arg SetHabitArchivedParams) (int64, error)
	UnmarkCompletion(ctx context.Context, arg UnmarkCompletionParams) error
}

var _ Querier = (*Queries)(nil)
