// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package timelinedb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ArchiveCategory(ctx context.Context, arg ArchiveCategoryParams) (int64, error)
	CountAssignableCategory(ctx context.Context, arg CountAssignableCategoryParams) (int64, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (CreateCategoryRow, error)
	CreateTimeBlock(ctx context.Context, arg CreateTimeBlockParams) (CreateTimeBlockRow, error)
	DeleteTimeBlock(ctx context.Context, arg DeleteTimeBlockParams) (int64, error)
	GetCategory(ctx context.Context, arg GetCategoryParams) (GetCategoryRow, error)
	GetTimeBlock(ctx context.Context, arg GetTimeBlockParams) (GetTimeBlockRow, error)
	ListActiveCategories(ctx context.Context, accountID uuid.UUID) ([]ListActiveCategoriesRow, error)
	ListBlocksOverlapping(ctx context.Context, arg ListBlocksOverlappingParams) ([]ListBlocksOverlappingRow, error)
	RenameCategory(ctx context.Context, arg RenameCategoryParams) (int64, error)
	UpdateTimeBlock(ctx context.Context, arg UpdateTimeBlockParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
