// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package timelinedb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archiveCategory = `-- name: ArchiveCategory :execrows
UPDATE categories
SET archived_at = now()
WHERE account_id = $1 AND id = $2 AND archived_at IS NULL
`

type ArchiveCategoryParams struct {
	AccountID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) ArchiveCategory(ctx context.Context, arg ArchiveCategoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, archiveCategory, arg.AccountID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countAssignableCategory = `-- name: CountAssignableCategory :one
SELECT count(*)
FROM categories
WHERE account_id = $1 AND id = $2 AND archived_at IS NULL
`

type CountAssignableCategoryParams struct {
	AccountID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) CountAssignableCategory(ctx context.Context, arg CountAssignableCategoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAssignableCategory, arg.AccountID, arg.ID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (account_id, name)
VALUES ($1, $2)
RETURNING id, name, archived_at, created_at
`

type CreateCategoryParams struct {
	AccountID uuid.UUID
	Name      string
}

type CreateCategoryRow struct {
	ID         uuid.UUID
	Name       string
	ArchivedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (CreateCategoryRow, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.AccountID, arg.Name)
	var i CreateCategoryRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createTimeBlock = `-- name: CreateTimeBlock :one
INSERT INTO time_blocks (account_id, kind, starts_at, ends_at, category_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, kind, starts_at, ends_at, category_id, created_at
`

type CreateTimeBlockParams struct {
	AccountID  uuid.UUID
	Kind       string
	StartsAt   pgtype.Timestamptz
	EndsAt     pgtype.Timestamptz
	CategoryID pgtype.UUID
}

type CreateTimeBlockRow struct {
	ID         uuid.UUID
	Kind       string
	StartsAt   pgtype.Timestamptz
	EndsAt     pgtype.Timestamptz
	CategoryID pgtype.UUID
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) CreateTimeBlock(ctx context.Context, arg CreateTimeBlockParams) (CreateTimeBlockRow, error) {
	row := q.db.QueryRow(ctx, createTimeBlock,
		arg.AccountID,
		arg.Kind,
		arg.StartsAt,
		arg.EndsAt,
		arg.CategoryID,
	)
	var i CreateTimeBlockRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.StartsAt,
		&i.EndsAt,
		&i.CategoryID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTimeBlock = `-- name: DeleteTimeBlock :execrows
DELETE FROM time_blocks
WHERE account_id = $1 AND id = $2
`

type DeleteTimeBlockParams struct {
	AccountID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) DeleteTimeBlock(ctx context.Context, arg DeleteTimeBlockParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTimeBlock, arg.AccountID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCategory = `-- name: GetCategory :one
SELECT id, name, archived_at, created_at
FROM categories
WHERE account_id = $1 AND id = $2
`

type GetCategoryParams struct {
	AccountID uuid.UUID
	ID        uuid.UUID
}

type GetCategoryRow struct {
	ID         uuid.UUID
	Name       string
	ArchivedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) GetCategory(ctx context.Context, arg GetCategoryParams) (GetCategoryRow, error) {
	row := q.db.QueryRow(ctx, getCategory, arg.AccountID, arg.ID)
	var i GetCategoryRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTimeBlock = `-- name: GetTimeBlock :one
SELECT id, kind, starts_at, ends_at, category_id, created_at
FROM time_blocks
WHERE account_id = $1 AND id = $2
`

type GetTimeBlockParams struct {
	AccountID uuid.UUID
	ID        uuid.UUID
}

type GetTimeBlockRow struct {
	ID         uuid.UUID
	Kind       string
	StartsAt   pgtype.Timestamptz
	EndsAt     pgtype.Timestamptz
	CategoryID pgtype.UUID
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) GetTimeBlock(ctx context.Context, arg GetTimeBlockParams) (GetTimeBlockRow, error) {
	row := q.db.QueryRow(ctx, getTimeBlock, arg.AccountID, arg.ID)
	var i GetTimeBlockRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.StartsAt,
		&i.EndsAt,
		&i.CategoryID,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveCategories = `-- name: ListActiveCategories :many
SELECT id, name, archived_at, created_at
FROM categories
WHERE account_id = $1 AND archived_at IS NULL
ORDER BY lower(name)
`

type ListActiveCategoriesRow struct {
	ID         uuid.UUID
	Name       string
	ArchivedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) ListActiveCategories(ctx context.Context, accountID uuid.UUID) ([]ListActiveCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listActiveCategories, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveCategoriesRow{}
	for rows.Next() {
		var i ListActiveCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ArchivedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlocksOverlapping = `-- name: ListBlocksOverlapping :many
SELECT b.id, b.kind, b.starts_at, b.ends_at, b.category_id, c.name AS category_name
FROM time_blocks b
LEFT JOIN categories c ON c.id = b.category_id
WHERE b.account_id = $1
  AND b.starts_at < $2
  AND b.ends_at > $3
ORDER BY b.starts_at, b.ends_at
`

type ListBlocksOverlappingParams struct {
	AccountID   uuid.UUID
	WindowEnd   pgtype.Timestamptz
	WindowStart pgtype.Timestamptz
}

type ListBlocksOverlappingRow struct {
	ID           uuid.UUID
	Kind         string
	StartsAt     pgtype.Timestamptz
	EndsAt       pgtype.Timestamptz
	CategoryID   pgtype.UUID
	CategoryName pgtype.Text
}

func (q *Queries) ListBlocksOverlapping(ctx context.Context, arg ListBlocksOverlappingParams) ([]ListBlocksOverlappingRow, error) {
	rows, err := q.db.Query(ctx, listBlocksOverlapping, arg.AccountID, arg.WindowEnd, arg.WindowStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBlocksOverlappingRow{}
	for rows.Next() {
		var i ListBlocksOverlappingRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.StartsAt,
			&i.EndsAt,
			&i.CategoryID,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameCategory = `-- name: RenameCategory :execrows
UPDATE categories
SET name = $3
WHERE account_id = $1 AND id = $2 AND archived_at IS NULL
`

type RenameCategoryParams struct {
	AccountID uuid.UUID
	ID        uuid.UUID
	Name      string
}

func (q *Queries) RenameCategory(ctx context.Context, arg RenameCategoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, renameCategory, arg.AccountID, arg.ID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTimeBlock = `-- name: UpdateTimeBlock :execrows
UPDATE time_blocks
SET starts_at = $3, ends_at = $4, category_id = $5
WHERE account_id = $1 AND id = $2
`

type UpdateTimeBlockParams struct {
	AccountID  uuid.UUID
	ID         uuid.UUID
	StartsAt   pgtype.Timestamptz
	EndsAt     pgtype.Timestamptz
	CategoryID pgtype.UUID
}

func (q *Queries) UpdateTimeBlock(ctx context.Context, arg UpdateTimeBlockParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTimeBlock,
		arg.AccountID,
		arg.ID,
		arg.StartsAt,
		arg.EndsAt,
		arg.CategoryID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
