// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package timelinedb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countBlocksByCategory = `-- name: CountBlocksByCategory :many
SELECT category_id, count(*) AS total
FROM time_blocks
WHERE account_id = $1 AND category_id IS NOT NULL
GROUP BY category_id
`

type CountBlocksByCategoryRow struct {
	CategoryID pgtype.UUID
	Total      int64
}

func (q *Queries) CountBlocksByCategory(ctx context.Context, accountID uuid.UUID) ([]CountBlocksByCategoryRow, error) {
	rows, err := q.db.Query(ctx, countBlocksByCategory, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountBlocksByCategoryRow{}
	for rows.Next() {
		var i CountBlocksByCategoryRow
		if err := rows.Scan(&i.CategoryID, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countBlocksByTask = `-- name: CountBlocksByTask :many
SELECT task_id, count(*) AS total
FROM time_blocks
WHERE account_id = $1 AND task_id IS NOT NULL
GROUP BY task_id
`

type CountBlocksByTaskRow struct {
	TaskID pgtype.UUID
	Total  int64
}

// A task-linked block's own category_id is always null (CHECK constraint); this
// powers the inherited-category count so a task-linked block still contributes to
// its (inherited) category's total in the categories overview (MX-TL).
func (q *Queries) CountBlocksByTask(ctx context.Context, accountID uuid.UUID) ([]CountBlocksByTaskRow, error) {
	rows, err := q.db.Query(ctx, countBlocksByTask, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountBlocksByTaskRow{}
	for rows.Next() {
		var i CountBlocksByTaskRow
		if err := rows.Scan(&i.TaskID, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createTimeBlock = `-- name: CreateTimeBlock :one
INSERT INTO time_blocks (account_id, kind, starts_at, ends_at, category_id, task_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, kind, starts_at, ends_at, category_id, task_id, created_at
`

type CreateTimeBlockParams struct {
	AccountID  uuid.UUID
	Kind       string
	StartsAt   pgtype.Timestamptz
	EndsAt     pgtype.Timestamptz
	CategoryID pgtype.UUID
	TaskID     pgtype.UUID
}

type CreateTimeBlockRow struct {
	ID         uuid.UUID
	Kind       string
	StartsAt   pgtype.Timestamptz
	EndsAt     pgtype.Timestamptz
	CategoryID pgtype.UUID
	TaskID     pgtype.UUID
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) CreateTimeBlock(ctx context.Context, arg CreateTimeBlockParams) (CreateTimeBlockRow, error) {
	row := q.db.QueryRow(ctx, createTimeBlock,
		arg.AccountID,
		arg.Kind,
		arg.StartsAt,
		arg.EndsAt,
		arg.CategoryID,
		arg.TaskID,
	)
	var i CreateTimeBlockRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.StartsAt,
		&i.EndsAt,
		&i.CategoryID,
		&i.TaskID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTimeBlock = `-- name: DeleteTimeBlock :execrows
DELETE FROM time_blocks
WHERE account_id = $1 AND id = $2
`

type DeleteTimeBlockParams struct {
	AccountID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) DeleteTimeBlock(ctx context.Context, arg DeleteTimeBlockParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTimeBlock, arg.AccountID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTimeBlock = `-- name: GetTimeBlock :one
SELECT id, kind, starts_at, ends_at, category_id, task_id, created_at
FROM time_blocks
WHERE account_id = $1 AND id = $2
`

type GetTimeBlockParams struct {
	AccountID uuid.UUID
	ID        uuid.UUID
}

type GetTimeBlockRow struct {
	ID         uuid.UUID
	Kind       string
	StartsAt   pgtype.Timestamptz
	EndsAt     pgtype.Timestamptz
	CategoryID pgtype.UUID
	TaskID     pgtype.UUID
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) GetTimeBlock(ctx context.Context, arg GetTimeBlockParams) (GetTimeBlockRow, error) {
	row := q.db.QueryRow(ctx, getTimeBlock, arg.AccountID, arg.ID)
	var i GetTimeBlockRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.StartsAt,
		&i.EndsAt,
		&i.CategoryID,
		&i.TaskID,
		&i.CreatedAt,
	)
	return i, err
}

const listAllBlocks = `-- name: ListAllBlocks :many
SELECT id, kind, starts_at, ends_at, category_id, task_id, created_at
FROM time_blocks
WHERE account_id = $1
ORDER BY starts_at
`

type ListAllBlocksRow struct {
	ID         uuid.UUID
	Kind       string
	StartsAt   pgtype.Timestamptz
	EndsAt     pgtype.Timestamptz
	CategoryID pgtype.UUID
	TaskID     pgtype.UUID
	CreatedAt  pgtype.Timestamptz
}

// Every planned and actual block, unbounded, for M8 export completeness.
func (q *Queries) ListAllBlocks(ctx context.Context, accountID uuid.UUID) ([]ListAllBlocksRow, error) {
	rows, err := q.db.Query(ctx, listAllBlocks, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllBlocksRow{}
	for rows.Next() {
		var i ListAllBlocksRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.StartsAt,
			&i.EndsAt,
			&i.CategoryID,
			&i.TaskID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlocksByTask = `-- name: ListBlocksByTask :many
SELECT id, kind, starts_at, ends_at, category_id, task_id
FROM time_blocks
WHERE account_id = $1 AND task_id = $2
ORDER BY starts_at
`

type ListBlocksByTaskParams struct {
	AccountID uuid.UUID
	TaskID    pgtype.UUID
}

type ListBlocksByTaskRow struct {
	ID         uuid.UUID
	Kind       string
	StartsAt   pgtype.Timestamptz
	EndsAt     pgtype.Timestamptz
	CategoryID pgtype.UUID
	TaskID     pgtype.UUID
}

// Every block (planned and actual, across any date) linked to one task —
// v1.md §7's "see all of a task's linked time blocks" (reverse of task_id).
func (q *Queries) ListBlocksByTask(ctx context.Context, arg ListBlocksByTaskParams) ([]ListBlocksByTaskRow, error) {
	rows, err := q.db.Query(ctx, listBlocksByTask, arg.AccountID, arg.TaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBlocksByTaskRow{}
	for rows.Next() {
		var i ListBlocksByTaskRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.StartsAt,
			&i.EndsAt,
			&i.CategoryID,
			&i.TaskID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlocksOverlapping = `-- name: ListBlocksOverlapping :many
SELECT b.id, b.kind, b.starts_at, b.ends_at, b.category_id, b.task_id
FROM time_blocks b
WHERE b.account_id = $1
  AND b.starts_at < $2
  AND b.ends_at > $3
ORDER BY b.starts_at, b.ends_at
`

type ListBlocksOverlappingParams struct {
	AccountID   uuid.UUID
	WindowEnd   pgtype.Timestamptz
	WindowStart pgtype.Timestamptz
}

type ListBlocksOverlappingRow struct {
	ID         uuid.UUID
	Kind       string
	StartsAt   pgtype.Timestamptz
	EndsAt     pgtype.Timestamptz
	CategoryID pgtype.UUID
	TaskID     pgtype.UUID
}

func (q *Queries) ListBlocksOverlapping(ctx context.Context, arg ListBlocksOverlappingParams) ([]ListBlocksOverlappingRow, error) {
	rows, err := q.db.Query(ctx, listBlocksOverlapping, arg.AccountID, arg.WindowEnd, arg.WindowStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBlocksOverlappingRow{}
	for rows.Next() {
		var i ListBlocksOverlappingRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.StartsAt,
			&i.EndsAt,
			&i.CategoryID,
			&i.TaskID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTimeBlock = `-- name: UpdateTimeBlock :execrows
UPDATE time_blocks
SET starts_at = $3, ends_at = $4, category_id = $5, task_id = $6
WHERE account_id = $1 AND id = $2
`

type UpdateTimeBlockParams struct {
	AccountID  uuid.UUID
	ID         uuid.UUID
	StartsAt   pgtype.Timestamptz
	EndsAt     pgtype.Timestamptz
	CategoryID pgtype.UUID
	TaskID     pgtype.UUID
}

func (q *Queries) UpdateTimeBlock(ctx context.Context, arg UpdateTimeBlockParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTimeBlock,
		arg.AccountID,
		arg.ID,
		arg.StartsAt,
		arg.EndsAt,
		arg.CategoryID,
		arg.TaskID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
