// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package timelinedb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountBlocksByCategory(ctx context.Context, accountID uuid.UUID) ([]CountBlocksByCategoryRow, error)
	// A task-linked block's own category_id is always null (CHECK constraint); this
	// powers the inherited-category count so a task-linked block still contributes to
	// its (inherited) category's total in the categories overview (MX-TL).
	CountBlocksByTask(ctx context.Context, accountID uuid.UUID) ([]CountBlocksByTaskRow, error)
	CreateTimeBlock(ctx context.Context, arg CreateTimeBlockParams) (CreateTimeBlockRow, error)
	DeleteTimeBlock(ctx context.Context, arg DeleteTimeBlockParams) (int64, error)
	GetTimeBlock(ctx context.Context, arg GetTimeBlockParams) (GetTimeBlockRow, error)
	// Every planned and actual block, unbounded, for M8 export completeness.
	ListAllBlocks(ctx context.Context, accountID uuid.UUID) ([]ListAllBlocksRow, error)
	// Every block (planned and actual, across any date) linked to one task —
	// v1.md §7's "see all of a task's linked time blocks" (reverse of task_id).
	ListBlocksByTask(ctx context.Context, arg ListBlocksByTaskParams) ([]ListBlocksByTaskRow, error)
	ListBlocksOverlapping(ctx context.Context, arg ListBlocksOverlappingParams) ([]ListBlocksOverlappingRow, error)
	UpdateTimeBlock(ctx context.Context, arg UpdateTimeBlockParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
